#!/bin/sh
set -e

lb config noauto \
  --mode debian \
  --system live \
  --distribution testing \
  --architectures amd64 \
  --archive-areas "main contrib non-free-firmware" \
  --security true \
  --updates true \
  --backports false \
  --binary-images iso-hybrid \
  --bootloaders "syslinux grub-efi" \
  --debian-installer live \
  --debian-installer-distribution testing \
  --debian-installer-gui true \
  --linux-flavours amd64 \
  --apt-indices false \
  --apt-recommends true \
  --firmware-chroot true \
  --firmware-binary true \
  --debootstrap-options "--variant=minbase" \
  --bootappend-live "boot=live components quiet splash persistence" \
  --iso-application "DakuOS" \
  --iso-publisher "DakuOS; https://github.com/ddr-ai/DakuOS" \
  --iso-volume "DakuOS $(date +%Y%m%d)" \
  "${@}"
